package com.example.composeapk

object infgames {
    val infgames = listOf(
        infgame(
            "1",
            "FIFA 23 secara resmi terungkap",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjS6boEO8kZRxDOGFViHEcB416vg49sdcYIZ93LSczWLa7_XPvY27B4lszrPwDUF4xh079l5Sega-COVrj-NvgZXY91yi2hgxYWjWs7hG_drJnKi-boiczi3KInXXoG5bLa21OodQDBQde9FO_k5oU8eeRc7RlcLNFgnUXBaBN3PbSnOZjyZjBolYgiDw/s750/FIFA-23-750x375.jpg",
            "FIFA 23 adalah angsuran terbaru dalam seri permainan sepak bola yang sudah berjalan lama yang bertujuan untuk memberikan pemain pengalaman otentik dari olahraga. EA akhirnya mengungkapkan FIFA 23 melalui trailer baru dan mengonfirmasi bahwa itu akan didukung oleh teknologi HyperMotion2. Teknologi HyperMotion adalah fokus besar dari upaya promosi FIFA 22, meskipun terbatas pada versi konsol game PS4.\n" + "\n" + "FIFA 23 dipastikan memiliki dukungan cross-play penuh di sebagian besar mode permainan. Komunitas tidak memiliki banyak informasi tentang FIFA 23 sebelumnya karena EA tidak mengadakan konferensi pers EA Play Live musim panas yang biasa tahun ini. Dengan trailer baru ini, EA memberikan gambaran sekilas kepada para penggemar tentang gameplay, grafik dan banyak lagi FIFA 23, dan mengonfirmasi tanggal rilis game tersebut."
        ),
        infgame(
            "2",
            "Persyaratan Sistem Marvel Spider-Man",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg72w8vm-SLSNGIClWSIths1xF16dzwKDEQ6sgWyHr-59KJs2IyWmMj7x723lgDZ3waWcIPU0pQ6uoikiwnq-sar792tt22DF0uZ0Slm-yBwtNpRZVupPtnqbGu52XOgqHvihSXzvNaUjhqFA3ljYZFH-RXKInyQsyWoTMY6tWRWeU9rDoNxRit1Rchzg/w640-h360/mar.jpg",
            "Sony dan Insomniac Games telah meluncurkan detail Spider-Man Remastered baru dengan trailer baru. Spider-Man Remastered akan rilis pada pada port pc pada 12 Agustus 2022. Anda juga dapat memesan di muka sekarang di Steam dan EGS. \n\nPersyaratan Minimum (720p/30 FPS/Pengaturan Sangat Rendah)\n\nOS: Windows 10 (64-bit)\nProsesor: Intel Core i3-4160  atau lebih baik\nVideo Card: NVIDIA GTX 950  atau lebih baik\nRAM: 8 GB\nFree space: 75 GB\nPersyaratan yang disarankan (pengaturan 1080p/60 FPS/sedang):\n\nOS: Windows 10 (64-bit)\nProsesor: Intel Core i5-4670 atau AMD Ryzen 5 1600 atau lebih baik\nVideo Card: GeForce GTX 1060 6GB atau AMD RX 580  atau lebih baik\nRAM: 16 GB\nFree space: 75 GB (SSD)",
        ),
        infgame(
            "3",
            "Soulframe adalah MMO baru dari pengembang Warframe",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi5hy-Hg_qEncf3t-v2rmDe7m64PsH7FY_dXkH2uF9_OWWl4-_mvbIsLMNJlueA2CW3wL0BKz-BmW6AvUSQNXgSTf4nYQZzQS_hjcn5fe0JcZN4vLfuoy8ksB4BT6zmod_KWo9ek0SjcTwIF_LacW4wv4c__dmIIpRdHoeQsvNkqUhOHdr5jANXS-x0hg/w640-h360/20227171003847_1.jpg.webp",
            "Digital Extremes, studio di balik game Warframe, telah menghabiskan hampir satu dekade berfokus hampir secara eksklusif pada produk andalannya. Selama waktu itu, beberapa rencana menjanjikan mereka lainnya, seperti The Amazing Eternals, gagal tanpa pernah mendapatkan produk akhir. Sekarang, bagaimanapun, studio telah mengumumkan Soulframe produk baru yang bisa menjadi fokus utama mereka berikutnya.\n\n \n\nMeskipun masih belum sepenuhnya jelas apakah Soulframe akan diatur dalam semesta Warframe sendiri, inspirasi visual di balik proyek baru ini memberikan gambaran yang jelas. Soulframe adalah MMORPG yang dapat menghadirkan pertarungan jarak dekat, di dunia yang terus berubah yang tampaknya merespons semacam perkembangan industri dengan berubah dari hari ke hari.\n\n \n\nDigital Extremes menjadi merek dagang Soulframe awal tahun ini, yang menyebabkan sedikit kebingungan di antara komunitas game Warframe. Sementara judulnya menyinggung hubungan langsung dengan Warframe, sepertinya ini bukan tujuan tim pengembangan. Meskipun pasti ada ruang bagi Soulframe untuk muncul dengan sendirinya, direktur Digital Extremes Steve Sinclair mengatakan bahwa judul tersebut akan berada di \"dunia cermin Warframe\", yang dapat memunculkan banyak ide untuk para penggemar.\n\n \n\nAnehnya, sebagian besar tim pengembangan Soulframe yang baru terbentuk berasal dari Warframe itu sendiri. Sinclair adalah salah satu direktur kreatif game sebelumnya (sekarang digantikan oleh mantan manajer komunitas Rebecca Ford) dan dia akan bergabung dengan Geoff Crookes, yang memiliki peran serupa untuk dimainkan dalam proyek tersebut. Pasangan ini tampak bersemangat tentang perpindahan ke produk unggulan baru Digital Extremes, yang menurut mereka akan terinspirasi oleh Princess Mononoke dan The NeverEnding Story, antara lain. Pada saat yang sama, pembaruan Duviri Paradox Warframe yang tertunda kembali ke jalurnya dan pengembangannya juga harus dilanjutkan.\n\n \n\nSalah satu kritik terbesar terhadap Warframe selama bertahun-tahun adalah bahwa ini adalah MMO yang kurang, dan Digital Extremes dapat menggunakan Soulframe untuk memberikan proyek dengan keseimbangan tema yang lebih baik. Berbagai fitur dan konten. Sebagai produk yang sepenuhnya baru, Soulframe akan memungkinkan DE untuk terus mengembangkan pengalaman gameplay yang berkembang tanpa terhalang oleh kekurangan Warframe.\n\n \n\nKarena Warframe secara luas dianggap sebagai salah satu game live-serve terbaik di pasaran, akan menarik untuk melihat apakah Digital Extremes dapat melakukan hal serupa dengan Soulframe. Karena game ini baru saja diumumkan secara resmi, sebagian besar masih menjadi misteri dan informasi lebih lanjut tentangnya akan diumumkan dalam beberapa bulan mendatang.",
        ),
        infgame(
            "4",
            "Spoiler One Piece 1054: Sabo masih hidup?",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhD-oWmLGNSXbNQe20yPSYICuuGsGE_KYklMlGBxSemPSLgq_qYGgtCQc6j2QTabh_dSA3hoX9_fVe1r6PnKSC1Hi0B-PhF398quxaFCIsrXMCIHgbi9tLkdbk9oTyLC4myBc6AgZy8whvb8xX4uwSfxBbqTjhsi0-Gz-e6CGhvUJHVONuCbnWuXgj2zA/w640-h426/920308997.png",
            "Spoiler One Piece 1054, ringkasan bab 1053: Setelah sebulan hiatus, OP 1054 akan kembali dengan perkembangan yang sangat tidak terduga. Akankah Laksamana Luc Niu menyerang New Yonko Luffy?\n\n \n\nOne Piece 1053 memberikan cukup banyak informasi penting bagi pembacanya. Dalam acara pertama, Lima Tetua berdiskusi dengan Marinir tentang karunia Luffy. Mereka meminta untuk menghapus Gear 5 dan menghapus \"D\" dari namanya. Angkatan Laut mengatakan bahwa mereka tidak dapat menghubungi penerbit (yaitu Morgans) dan sekarang sudah terlambat untuk mengubah keadaan.\n\n \n\nLaksamana Luc Niu sedang menuju ke Huadu. Menurut Lag, tidak, saya tidak \"gila\" datang ke sini untuk menantang. Bab 1054 akan menjadi awal dari Saga terakhir One Piece, jadi ada kemungkinan Enam Banteng ada di sini untuk bertukar sesuatu dengan Luffy. Mungkin juga alasan Enam Banteng datang ke Wano adalah karena dia mengincar Senjata Kuno Pluton!\n\n \n\nMengetahui bahwa istirahat selama sebulan, penulis Oda telah mengajukan terlalu banyak pertanyaan kepada pembaca. Bagaimana nasib Kaido dan Big Mom? Seorang pria CP0 mengatakan dia melihat kapal Big Mom, jadi mungkin kru Big Mom akan menyelamatkan dua mantan Yonko? Bagaimana dengan Sabo? Menurut informasi, Luc Niu bertemu dengan Sabo dan sekarang dia ada di sini! Mungkinkah Sabo benar-benar mati? Pertanyaan-pertanyaan ini mungkin akan terjawab di One Piece 1054 - 1055.\n\n \n\nJudul One Piece 1054: Kaisar Api. Ini adalah nama jurus Ace, jadi sepertinya chapter ini banyak menutupinya. Karena Buah Iblis Ace sekarang menjadi milik Sabo, menurut spoiler, Sabo juga disebutkan.\n\n \n\nBab ini membahas tentang kematian karakter tertentu. Rupanya bukan Sabo karena \"orang ini terkait dengan Sabo\". Mungkinkah apakah itu Vivi?. Saya memiliki beberapa informasi lebih lanjut tentang Six Bulls Aramaki. Buah Iblisnya bertipe Logia.",
        ),
        infgame(
            "5",
            "Kona 2 Akan rilis tahun 2023",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh4Kab0CdkKos1HyWkV_oGH77se2VFlYqVDdNxfEGMyLz5EAj4bXDcoWmd7X6Z6HXP7UOrLtc778snlOLalLctk2ihiMZcS701khTklcT0ylxL_7LRtJYCWQYBe_tnymNaDFANAMkgMT3kkG0kRrx5zaVxxDcqq0LnEwlObksxrSqdtOa0S-v5-6QHWmQ/w640-h360/Kona-2-Brume-announced-with-trailer-release-in-2023-on.jpg",
            "Parabole telah mengumumkan Kona 2: Brume dengan trailer  baru dari seri ini akan dirilis pada tahun 2023 di PC, PS5, PS4, Xbox Series X | S, Xbox One, dan Nintendo Switch.\n\n \n\nSekuel Kona baru akan melihat kita menjelajahi Quebec Utara sebagai bagian dari cerita yang terjadi pada tahun 1970 dan berputar di sekitar Kabut , kabut misterius yang tiba-tiba menyelimuti sebuah desa yang tenang.\n\n \n\nTujuan utama Kona 2: Brume adalah untuk menguraikan apa yang tersembunyi di balik kabut aneh dan tebal yang mencapai sejauh mata memandang . Dalam posisi Detektif Carl Faubert, kita harus menyelidiki semua yang ada di sekitar kita, sementara kita membuat catatan di buku harian dan mencoba bertahan baik dalam kondisi cuaca yang sangat agresif maupun ancaman lain yang berada di luar pemahaman kita. Menurut laman Steam, cerita dan karakternya akan menjadi elemen yang sangat penting.\n\n \n\n\"Ikuti petunjuk dan petunjuk dengan sangat hati-hati. Konsultasikan buku harian Carl Faubert dan uji keterampilan detektif Anda. Apakah Anda dapat mengumpulkan misteri di balik Kabut?\", Membaca sinopsis resmi permainan.\n\n \n\n\"Kabut tak terhindarkan: badai salju yang membekukan, binatang berbahaya, dan mimpi buruk yang mengganggu. Bersiaplah untuk bertahan melawan segala rintangan. Sebuah kisah menarik untuk ditemukan selangkah demi selangkah.\" \"Temukan dan periksa objek, surat, dan dokumen, sementara narator mahatahu menceritakan petualangan Anda di Manastan.\"",
        ),
        infgame(
            "6",
            "Nintendo mengumumkan akuisisi studio film Dynamo Pictures",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDo1CUSJFvCIRYBAdWpzudC8JThkU9wJtbB3J1sA4BXbLIIF1ZztIhDXNZl6i7dqs3zgFknbPwV2101Z4rQGykEMwV_-OQe_ks6NyOlj7_HsyIyzm0u_KWjt2ILouVJjeWT8XbDLEo1-hF6A9N6gqC4sY2NdT85iCBhwO0S6ql1uKsaz_8KFm0dUUkKw/w640-h360/nintendo-ntdoy-acquires-anime-and-cg-studio-dynamo-pictures_feature.webp",
            "Sejarah sinematik Nintendo telah memburuk sejak rilis Super Mario Bros pada tahun 1993, yang dianggap oleh banyak orang sebagai salah satu adaptasi video game terburuk sepanjang masa. Ini mungkin mencegah Nintendo dari melisensikan kekayaan intelektual ke film sejak dirilis. Nintendo telah membeli Dynamo Pictures, sebuah studio produksi CG yang berbasis di Tokyo yang akan berganti nama menjadi Nintendo Pictures, menurut pengajuan baru-baru ini dari raksasa video game Jepang. Akuisisi dan perubahan nama diproyeksikan akan selesai pada 3 Oktober.\n\n \n\nPerilisan film tahun 1993 Super Mario Bros, disutradarai oleh Rocky Morton dan Annabel Jankel, disambut dengan reaksi negatif yang meluas dari penonton dan kritikus, dengan banyak yang berpendapat bahwa film tersebut gagal untuk berhasil, dengan hormat mengadaptasi serial tersebut. Pencipta Mario Shigeru Miyamoto bahkan mengomentari ini sekali dalam sebuah wawancara, mengklaim bahwa film tersebut menghabiskan lebih banyak waktu untuk merujuk permainan daripada sebenarnya film yang menghibur. Hal ini mendorong Miyamoto untuk memulai negosiasi dengan studio yang membuat \"Moon Thieves\" - Illumination pada tahun 2016, memperbaharui minat terhadap film animasi Super Mario Bros yang saat ini sedang dalam produksi dan akan dirilis bulan depan April 2023. Miyamoto akan bertindak sebagai produser pada film tersebut.\n\n \n\nDengan minat baru dalam film dan adaptasi TV, sepertinya Nintendo siap untuk mulai mengerjakan lebih banyak proyek seperti film Mario yang akan datang. Salah satunya bisa dimulai dengan membangun studio in-house, setidaknya jika akuisisi terbaru mereka atas Dynamo Pictures bisa dilakukan. Nintendo sebelumnya bermitra dengan Dynamo pada franchise Pikmin Short Movies. dan studio mendukung pengembangan Metroid Other M.\n\n \n\nMeskipun mudah untuk berasumsi bahwa Nintendo Pictures yang baru dibentuk terutama akan fokus pada mengadaptasi produk Nintendo ke film dan media lain, mungkin juga Nintendo mengakuisisi Dynamo Pictures untuk dorongan. CG bekerja untuk game dan pemasarannya. Banyak penerbit memiliki studio in-house yang terutama didedikasikan untuk animasi CG, seperti Image Studio Division Square Enix, yang telah membuat cutscene untuk game seperti Kingdom Hearts 3, Final Fantasy 7 Remake, dan Shadow of the Tomb Raider, bersama dengan proyek film besar. seperti yang disebutkan sebelumnya Final Fantasy 7: Advent Children dan Kingsglaive: Final Fantasy 15.",
        ),
        infgame(
            "7",
            "Bayonetta 3 akhirnya memiliki tanggal rilis!",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjRt4QqhYD1I7P_sJzVh3yscKNMb7GicdOpC80zFB9gu-PYcEnkbgKpA-LMckVxzgmTTNg3AbGr8l9roKetF7AeRzEfJ1EBM9ngX0f-rNd63vD2JeuIRNo6TQndnIzZa_sXPoiztwqOdRe0-XBbAN3KhKdIqt4SrtDlthWbPuVymE3H5x2lwcq-tgXhKA/w640-h360/By2.jpg",
            "Bayonetta 3 akan diluncurkan pada 28 Oktober sebagai Nintendo Switch eksklusif, Nintendo dan PlatinumGames mengumumkan pada hari rabu ini. Sebuah trailer baru untuk game ini juga mengungkapkan detail baru tentang game aksi yang telah lama ditunggu-tunggu, termasuk bahwa game itu akan menampilkan beberapa Bayonetta dan Viola.\n\n \n\nViola digambarkan sebagai sekutu Bayonetta yang akan membawa pedang dan iblis kucingnya Cheshire ke dalam pertempuran melawan Homunculi. Bayonetta sendiri juga akan memiliki kemampuan Demon Masquerade baru, memanggil makhluk raksasa (seperti binatang tarantula jahat) untuk membantunya dalam pertempuran.\n\n“Dalam angsuran ketiga dari seri Bayonetta ini, Umbra Witch yang tak terbendung harus bergabung dengan beberapa wajah yang dikenalnya, Viola misterius dan banyak Bayonetta lainnya untuk menghentikan Homunculi buatan manusia dari mendatangkan malapetaka,” kata Nintendo.\n\n \n\n“Dalam permainan, Anda akan menggunakan senjata jahat Bayonetta dan kemampuan Demon Masquerade baru yang kuat untuk meledakkan, menginjak dan membanting musuh dengan kombo over-the-top yang menarik dan kekuatan iblis. Buktikan bahwa Anda adalah penyihir paling jahat dengan memerangi kejahatan yang bertekad menjerumuskan umat manusia ke dalam kekacauan.”\n\n \n\nNintendo juga menawarkan Trinity Masquerade Edition di toko tertentu dan Nintendo Store miliknya sendiri. Versi itu akan mencakup buku seni 200 halaman dan tiga kotak permainan dengan karya seni yang dapat dibalik untuk setiap judul dalam trilogi. Detail pre-order akan datang, kata Nintendo.",
        ),
        infgame(
            "8",
            "Baldur's Gate: Dark Alliance 2 remaster akan datang minggu depan",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjesSA33JMpLKcDW27IS1Hk-Mo2GOuUPbpq3vpEBu7GVRxJIaHiktcJgbwwPv-GUOAjYi4Vkl_NP8_x8w_6FCp-WvalLBSBMM4goP-THo0rODRXjSnlr86751jPr_sPE70pL1rV0kIHryCD7cPrGo80rYdHCnCTdA6mFYhrNdY1IEtzzjRf1uKSHlKb9w/w640-h360/dark.jpg",
            "Bulan lalu, penerbit Interplay dan pengembang Black Isle Studios mengumumkan pekerjaan yang sedang berlangsung pada remaster dari game action role-playing 2004 Baldur's Gate Dark Alliance 2.\n\n \n\nSetelah hanya ada pembicaraan tentang rilis musim panas ini, edisi baru diberi tanggal rilis konkret hari ini. Telah diumumkan bahwa Baldur's Gate Dark Alliance 2 akan tersedia pada 20 Juli 2022 untuk PC, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S dan Nintendo Switch.\n\nSejalan dengan pengungkapan tanggal rilis, detail teknis tentang remaster dari game action role-playing diberikan. Oleh karena itu, Baldur's Gate Dark Alliance 2 dapat dimainkan dalam resolusi 4K pada perangkat keras yang sesuai dan mendukung fitur coop. Juga dijanjikan empat tingkat kesulitan yang berbeda, akting suara penuh untuk dialog dan berbagai peningkatan teknis seperti tekstur baru, animasi karakter yang dioptimalkan, dan banyak lagi.\n\n \n\n\"Apakah Anda memilih Barbarian, Monk, Necromancer, Rogue, atau Cleric, pemain harus secara aktif bertarung melalui gerombolan monster seperti hobgoblin, ghoul, golem, dan naga sambil menghindari serangan dan jebakan mematikan.",
        ),
        infgame(
            "9",
            "Rockstar Membatalkan Port Red Dead Redemption 2 PS5 & Xbox Series X|S",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiJnA5uiULkMiQdE63mkEDar2K4fpYJqYx18_MF2lCRPN1G5HQYoyVYzje8rlYhblU89NJdKkAnxCqX7a83FenUP6XDwtQWNV6w5HFEorvmOBQiK2dwpV9xwrjGHblqMXwVCv6TYTUYhxwRPtYbbTQ3KbOnniBr3-pIUbfV6tKEu-OFvYysm5PUIXgD0g/w640-h360/rdr2.jpg",
            "Pembocor Rockstar Games yang terkenal telah menyatakan bahwa Red Dead Redemption 2 tidak akan menerima peningkatan pada generasi konsol baru. Rockstar memiliki sejarah merilis versi baru dari judul mereka di berbagai generasi konsol, terutama dengan seri Grand Theft Auto. Grand Theft Auto V 2013 yang awalnya diluncurkan di PlayStation 3 dan Xbox 360 telah dirilis ulang pada generasi konsol dan menerima peningkatan lain untuk PlayStation 5 dan Xbox Series X/S pada Maret 2022 .\n\n \n\nNamun, franchise Rockstar Red Dead Redemption kurang mendapat perhatian dalam hal rilis ulang meskipun sukses komersial dan kritis, dengan entri terbarunya, Red Dead Redemption 2, terjual lebih dari 44 juta kopi pada Mei 2022. Rumor telah Red Dead Redemption 2010 dijadwalkan untuk dibuat ulang bersama GTA 4 untuk membawanya ke konsol modern dan mungkin untuk pertama kalinya di PC. Namun, rencana ini dikatakan telah dibatalkan setelah peluncuran Grand Theft Auto: The Trilogy The Definitive Edition, yang hampir dikritik karena banyak bug dan kurangnya fitur.\n\n \n\nPembocor Rockstar Tez2 baru-baru ini mengumumkan pada 4 Juli bahwa pembaruan generasi baru Red Dead Redemption 2 untuk PlayStation 5 & Xbox Series S/X akan segera hadir, tetapi sekarang sepertinya orang ini telah kembali untuk menegaskan kembali pernyataannya sebelumnya. Videotech_ turun ke Twitter untuk membagikan tangkapan layar terbaru dari komentar terbaru Tez2 seputar masalah ini, yang menyatakan bahwa peningkatan konsol generasi berikutnya Red Dead Redemption 2 bersama dengan rencana oleh Rockstar tentang versi yang disempurnakan dari Editor Rockstar dibatalkan bersama dengan yang dilaporkan sebelumnya remake dari GTA 4 dan Red Dead Redemption.\n\nSetelah dirilis, Red Dead Redemption 2 dipuji karena dunianya yang sangat detail dan mengesankan secara visual yang mendorong batas kemampuan perangkat keras, jadi semoga rilis generasi baru terutama akan berfokus pada resolusi 4K dan frame rate yang lebih tinggi serta memanfaatkan PS5. DualSense  yang merupakan fitur yang dapat diperbarui seperti banyak judul terbaru lainnya.\n\n\n\nRockstar belum membuat pernyataan resmi tentang masalah ini, meskipun versi generasi baru dari Red Dead Redemption 2 tidak pernah diumumkan secara resmi sejak awal, jadi sepertinya pengembang tidak akan melakukannya. Sementara berita ini kemungkinan akan mengecewakan penggemar Red Dead, fokus Rockstar pada Grand Theft Auto 6 adalah kabar baik bagi penggemar Grand Theft Auto yang telah menantikan sekuelnya, dan sebagian besar mengkritik tindakan berulang kali merilis ulang GTA 5 selama beberapa tahun terakhir. dekade terakhir. Meskipun sangat sedikit yang diketahui tentang GTA 6 selain rumor dan kebocoran yang belum dikonfirmasi, Rockstar secara resmi mengkonfirmasi bahwa mereka secara aktif mengembangkan judul yang berarti penggemar tidak memiliki terlalu banyak waktu untuk menunggu.",
        ),
        infgame(
            "10",
            "Netflix Series Kingdom Mendapatkan Adaptasi Game Mobile dan PC",
            "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgnnaZ60Hhl4AAEWsd8QXtpiMgpnlfWD6Jei2VnACA7c45eOMgNvzllmuQ9VKQbb2NXuZj4qZFB9RQ0CspFa_WfdAhJiNqiatObHoPfzk_zhB0L88piLjZQ2P3rQXdQBoKuxSZUQBoxAf-6Acpf2bH6vKt1Lsuee6afi3BGEGgUPbxZAUkzu8KRouk5ng/w640-h360/kingdom-blogroll-1657327693650.png",
            "Netflix dan Action Square Korea telah mengumumkan Action RPG Kingdom: The Blood, yang akan dirilis untuk perangkat iOS, Android, dan PC.\n\nKingdom: The Blood akan menampilkan elemen PvP dan PvE, mode cerita yang mengikuti seri Netflix, dan mode pertempuran lima menit yang disebut Conquest. mengikuti peristiwa yang terlihat dalam seri dengan nama yang sama, sehingga Anda dapat menghadapi zombie dengan kualitas grafis yang tinggi.\n\n \n\nAction Square memastikan bahwa budaya Korea akan diperlakukan dengan \"sangat hati-hati dalam gameplay dan estetika.\" Studio menggunakan penari pedang profesional Korea untuk meniru pertarungan gaya Korea dengan benar. Selain itu, pemain akan memiliki berbagai pilihan kostum untuk menyesuaikan karakter mereka, termasuk Hanbok (pakaian tradisional Korea), yang menampilkan warna dan tekstur dalam yang mewakili Korea abad ke-16.\n\n \n\nTempat-tempat indah di Korea yang Anda lihat di serial ini akan dibuat ulang dalam game dan Kingdom: The Blood akan memiliki mode cerita yang mengikuti seri dan mode Penaklukan juga telah diumumkan, di mana Anda akan menghadapi pertempuran menantang yang berurutan. Plus, Anda akan memiliki pertempuran bos akhir level epik dan aksi melawan pemain lain jika Anda mau.\n\n \n\nTidak memiliki tanggal rilis Kingdom: The Blood sedang dikembangkan dengan mempertimbangkan pemirsa global sebagai upaya terbaru Netflix ke dalam industri video game.",
        )
    )
}